import { useState } from "react";
import { X, Loader2, Plus, Minus } from "lucide-react";
import apiClient from "../api/axios";
import { useToast } from "../context/ToastContext";
import ImageUpload from "./ImageUpload";

const TAG_OPTIONS = ["featured", "new_arrival", "best_seller", "trending"];
const STATUS_OPTIONS = ["in_stock", "out_of_stock", "discontinued"];

const INITIAL_FORM_DATA = {
  productName: "",
  productImg: "",
  secondaryImages: [""],
  productDes: "",
  sellingPrice: "",
  productCategory: "",
  productQuantity: 0,
  productStatus: "",
  tags: [],
  productSubDes: "",
  productSubCategory: "",
  dimensions: { length: "", breadth: "", height: "" },
};

/**
 * Validates product form data.
 * Returns { valid: boolean, errors: string[] }
 *
 * @param {object} formData - The form data to validate
 * @returns {{ valid: boolean, errors: string[] }}
 */
export function validateProductForm(formData) {
  const errors = [];

  if (!formData.productName || !formData.productName.trim()) {
    errors.push("Product name is required");
  }
  if (!formData.productImg || !formData.productImg.trim()) {
    errors.push("Product image URL is required");
  }
  if (!formData.productDes || !formData.productDes.trim()) {
    errors.push("Product description is required");
  }
  if (
    formData.sellingPrice === "" ||
    formData.sellingPrice === null ||
    formData.sellingPrice === undefined
  ) {
    errors.push("Selling price is required");
  } else if (Number(formData.sellingPrice) < 10) {
    errors.push("Selling price must be at least 10");
  }
  if (!formData.productCategory || !formData.productCategory.trim()) {
    errors.push("Product category is required");
  }
  if (!formData.productStatus || !formData.productStatus.trim()) {
    errors.push("Product status is required");
  }

  return { valid: errors.length === 0, errors };
}

/**
 * Builds the request payload for creating a product.
 * Excludes productId and uiProductId (auto-generated by backend).
 *
 * @param {object} formData - The form data
 * @returns {object} The request body for POST /admin/add/inventory
 */
export function buildCreatePayload(formData) {
  const payload = {
    productName: formData.productName,
    productImg: formData.productImg,
    productDes: formData.productDes,
    sellingPrice: Number(formData.sellingPrice),
    productCategory: formData.productCategory,
    productQuantity: Number(formData.productQuantity) || 0,
    productStatus: formData.productStatus,
    tags: formData.tags || [],
  };

  // Secondary images — filter out empty strings
  const secondaryImages = (formData.secondaryImages || []).filter(
    (url) => url && url.trim()
  );
  if (secondaryImages.length > 0) {
    payload.secondaryImages = secondaryImages;
  }

  // Dimensions — include only if at least one value is provided
  const dims = formData.dimensions || {};
  const hasAnyDim =
    dims.length !== "" || dims.breadth !== "" || dims.height !== "";
  if (hasAnyDim) {
    payload.dimensions = {};
    if (dims.length !== "") payload.dimensions.length = Number(dims.length);
    if (dims.breadth !== "") payload.dimensions.breadth = Number(dims.breadth);
    if (dims.height !== "") payload.dimensions.height = Number(dims.height);
  }

  if (formData.productSubDes && formData.productSubDes.trim()) {
    payload.productSubDes = formData.productSubDes;
  }
  if (formData.productSubCategory && formData.productSubCategory.trim()) {
    payload.productSubCategory = formData.productSubCategory;
  }

  return payload;
}

/**
 * AddProductForm — Modal overlay with a form for creating a new product.
 *
 * Props:
 *   onClose   — called to close the modal
 *   onSuccess — called after a product is successfully created
 */
export default function AddProductForm({ onClose, onSuccess }) {
  const { showToast } = useToast();
  const [formData, setFormData] = useState({ ...INITIAL_FORM_DATA });
  const [formErrors, setFormErrors] = useState([]);
  const [submitting, setSubmitting] = useState(false);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleDimensionChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      dimensions: { ...prev.dimensions, [name]: value },
    }));
  };

  const handleSecondaryImageChange = (index, value) => {
    setFormData((prev) => {
      const updated = [...prev.secondaryImages];
      updated[index] = value;
      return { ...prev, secondaryImages: updated };
    });
  };

  const addSecondaryImageField = () => {
    setFormData((prev) => ({
      ...prev,
      secondaryImages: [...prev.secondaryImages, ""],
    }));
  };

  const removeSecondaryImageField = (index) => {
    setFormData((prev) => ({
      ...prev,
      secondaryImages: prev.secondaryImages.filter((_, i) => i !== index),
    }));
  };

  const handleTagToggle = (tag) => {
    setFormData((prev) => {
      const tags = prev.tags.includes(tag)
        ? prev.tags.filter((t) => t !== tag)
        : [...prev.tags, tag];
      return { ...prev, tags };
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setFormErrors([]);

    const { valid, errors } = validateProductForm(formData);
    if (!valid) {
      setFormErrors(errors);
      return;
    }

    setSubmitting(true);
    try {
      const payload = buildCreatePayload(formData);
      await apiClient.post("/admin/add/inventory", payload);
      showToast("Product created successfully", "success");
      onSuccess();
      onClose();
    } catch (err) {
      const message =
        err.response?.data?.message || "Failed to create product";
      showToast(message, "error");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/50"
        onClick={onClose}
      />

      {/* Modal */}
      <div className="relative bg-white rounded-lg shadow-xl w-full max-w-2xl max-h-[90vh] overflow-y-auto mx-4">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200">
          <h2 className="text-lg font-semibold text-gray-900">Add New Product</h2>
          <button
            onClick={onClose}
            className="p-1 rounded-md hover:bg-gray-100 transition-colors"
          >
            <X className="h-5 w-5 text-gray-500" />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="px-6 py-4 space-y-4">
          {/* Validation errors */}
          {formErrors.length > 0 && (
            <div className="bg-red-50 border border-red-200 rounded-lg p-3">
              <ul className="list-disc list-inside text-sm text-red-700 space-y-1">
                {formErrors.map((err, i) => (
                  <li key={i}>{err}</li>
                ))}
              </ul>
            </div>
          )}

          {/* Product Name */}
          <div>
            <label htmlFor="productName" className="block text-sm font-medium text-gray-700 mb-1">
              Product Name <span className="text-red-500">*</span>
            </label>
            <input
              id="productName"
              name="productName"
              type="text"
              value={formData.productName}
              onChange={handleChange}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent"
              placeholder="Enter product name"
            />
          </div>

          {/* Primary Image */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Primary Image <span className="text-red-500">*</span>
            </label>
            <div className="flex items-start gap-3">
              <ImageUpload
                value={formData.productImg}
                onChange={(url) => setFormData((prev) => ({ ...prev, productImg: url }))}
                onRemove={() => setFormData((prev) => ({ ...prev, productImg: "" }))}
                label="Upload Primary Image"
              />
              <div className="flex-1">
                <input
                  id="productImg"
                  name="productImg"
                  type="text"
                  value={formData.productImg}
                  onChange={handleChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent"
                  placeholder="Or paste image URL"
                />
              </div>
            </div>
          </div>

          {/* Secondary Images */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Secondary Images
            </label>
            <div className="flex flex-wrap gap-3">
              {formData.secondaryImages.map((url, index) => (
                <ImageUpload
                  key={index}
                  value={url}
                  onChange={(newUrl) => handleSecondaryImageChange(index, newUrl)}
                  onRemove={() => removeSecondaryImageField(index)}
                  label={`Image ${index + 1}`}
                />
              ))}
              <button
                type="button"
                onClick={addSecondaryImageField}
                className="flex flex-col items-center justify-center border-2 border-dashed border-gray-300 rounded-lg h-24 w-24 hover:border-gray-400 transition-colors"
              >
                <Plus className="h-5 w-5 text-gray-400" />
                <span className="text-xs text-gray-500 mt-1">Add</span>
              </button>
            </div>
          </div>

          {/* Dimensions */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Dimensions (cm)
            </label>
            <div className="grid grid-cols-3 gap-3">
              <div>
                <input
                  name="length"
                  type="number"
                  min="0"
                  step="0.1"
                  value={formData.dimensions.length}
                  onChange={handleDimensionChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent"
                  placeholder="Length"
                />
              </div>
              <div>
                <input
                  name="breadth"
                  type="number"
                  min="0"
                  step="0.1"
                  value={formData.dimensions.breadth}
                  onChange={handleDimensionChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent"
                  placeholder="Breadth"
                />
              </div>
              <div>
                <input
                  name="height"
                  type="number"
                  min="0"
                  step="0.1"
                  value={formData.dimensions.height}
                  onChange={handleDimensionChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent"
                  placeholder="Height"
                />
              </div>
            </div>
          </div>

          {/* Product Description */}
          <div>
            <label htmlFor="productDes" className="block text-sm font-medium text-gray-700 mb-1">
              Description <span className="text-red-500">*</span>
            </label>
            <textarea
              id="productDes"
              name="productDes"
              value={formData.productDes}
              onChange={handleChange}
              rows={3}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent resize-vertical"
              placeholder="Enter product description"
            />
          </div>

          {/* Selling Price + Category (side by side) */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label htmlFor="sellingPrice" className="block text-sm font-medium text-gray-700 mb-1">
                Selling Price <span className="text-red-500">*</span>
              </label>
              <input
                id="sellingPrice"
                name="sellingPrice"
                type="number"
                min="10"
                step="0.01"
                value={formData.sellingPrice}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent"
                placeholder="10.00"
              />
            </div>
            <div>
              <label htmlFor="productCategory" className="block text-sm font-medium text-gray-700 mb-1">
                Category <span className="text-red-500">*</span>
              </label>
              <input
                id="productCategory"
                name="productCategory"
                type="text"
                value={formData.productCategory}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent"
                placeholder="e.g. Electronics"
              />
            </div>
          </div>

          {/* Quantity + Status (side by side) */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label htmlFor="productQuantity" className="block text-sm font-medium text-gray-700 mb-1">
                Quantity
              </label>
              <input
                id="productQuantity"
                name="productQuantity"
                type="number"
                min="0"
                value={formData.productQuantity}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent"
                placeholder="0"
              />
            </div>
            <div>
              <label htmlFor="productStatus" className="block text-sm font-medium text-gray-700 mb-1">
                Status <span className="text-red-500">*</span>
              </label>
              <select
                id="productStatus"
                name="productStatus"
                value={formData.productStatus}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent bg-white"
              >
                <option value="">Select status</option>
                {STATUS_OPTIONS.map((status) => (
                  <option key={status} value={status}>
                    {status.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())}
                  </option>
                ))}
              </select>
            </div>
          </div>

          {/* Tags (multi-select checkboxes) */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Tags</label>
            <div className="flex flex-wrap gap-3">
              {TAG_OPTIONS.map((tag) => (
                <label
                  key={tag}
                  className="inline-flex items-center gap-2 cursor-pointer"
                >
                  <input
                    type="checkbox"
                    checked={formData.tags.includes(tag)}
                    onChange={() => handleTagToggle(tag)}
                    className="h-4 w-4 rounded border-gray-300 text-gray-900 focus:ring-gray-900"
                  />
                  <span className="text-sm text-gray-700">
                    {tag.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())}
                  </span>
                </label>
              ))}
            </div>
          </div>

          {/* Sub Description */}
          <div>
            <label htmlFor="productSubDes" className="block text-sm font-medium text-gray-700 mb-1">
              Sub Description
            </label>
            <textarea
              id="productSubDes"
              name="productSubDes"
              value={formData.productSubDes}
              onChange={handleChange}
              rows={2}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent resize-vertical"
              placeholder="Optional sub description"
            />
          </div>

          {/* Sub Category */}
          <div>
            <label htmlFor="productSubCategory" className="block text-sm font-medium text-gray-700 mb-1">
              Sub Category
            </label>
            <input
              id="productSubCategory"
              name="productSubCategory"
              type="text"
              value={formData.productSubCategory}
              onChange={handleChange}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent"
              placeholder="Optional sub category"
            />
          </div>

          {/* Footer buttons */}
          <div className="flex items-center justify-end gap-3 pt-4 border-t border-gray-200">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={submitting}
              className="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-gray-900 rounded-lg hover:bg-gray-800 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {submitting && <Loader2 className="h-4 w-4 animate-spin" />}
              {submitting ? "Creating..." : "Create Product"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
